### ISSUE TITLE
[Suggestion] INSTALL.md

### ISSUE THREAD

**Issue by LOuroboros** [EternalCode/BW-hpbars#2]
Title is self-explanatory. How about adding a quick INSTALL.md document that explained the basic steps to set this up and inject the code into a Pokémon Fire Red ROM?

**Comment by EternalCode** [comment]
This project is dated now. There are features most games want to support like Mega Evolution which would be unhandled here. Moreover, I ported and revamped the source for this this over in the Commhack repository along with some work to automate battle background insertions. I recommend using that instead. See the HPbox branch.

**Comment by LOuroboros** [comment]
People who want to use mega evolutions would surely not come to this repository for that, I mean, its name is self-explanatory. It is a repository that inserts BW or BW2 styled HP Boxes/Bars into your ROM.

About the latter, the point still stands: There isn't a document for beginners to learn about inserting that specific code into a ROM, not here nor in that branch of the deceased CommHack.
The installation instructions written there seem to be for compiling a ROM. I could be wrong though.
